Repository micronaut-projects/micronaut-starter, pull requests merged in 2020-08, with the labels that each got.

#388 build: bump up to spock 2.0-M3-groovy-3.0
  gradle.properties
Labels: relates-to: build

#396 remove alpha
  starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/template/gcpFunctionReadme.rocker.raw
Labels: type: docs

#394 don't include in README instructions to run locally if it is function
  starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/GoogleCloudFunction.java
  starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/template/gcpFunctionReadme.rocker.raw
Labels: type: docs

#403 fix: Don't allow micronaut as app name
  starter-api/src/main/java/io/micronaut/starter/api/create/AbstractCreateController.java
  starter-cli/build.gradle
  starter-cli/src/main/java/io/micronaut/starter/cli/command/CreateCommand.java
  starter-cli/src/test/groovy/io/micronaut/starter/cli/command/CreateAppCommandSpec.groovy
  starter-core/src/main/java/io/micronaut/starter/application/Project.java
  starter-core/src/main/java/io/micronaut/starter/application/ProjectIdentifier.java
  starter-core/src/main/java/io/micronaut/starter/util/NameUtils.java
  starter-web-netty/src/test/groovy/io/micronaut/starter/netty/CreateControllerSpec.groovy
Labels: type: bug

#407 Updated oracle driver coordinates.
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/templates/buildGradle.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/build/maven/templates/pom.rocker.raw
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/OracleSpec.groovy
Labels: relates-to: build, type: improvement

#409 fix: add servlet for google-cloud-function & spock
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/templates/buildGradle.rocker.raw
Labels: type: bug

#410 test: TestFramework:getSourcePath
  starter-core/src/test/groovy/io/micronaut/starter/options/TestFrameworkSpec.groovy
Labels: type: improvement

#414 refactor: extract path
  starter-cli/src/main/java/io/micronaut/starter/cli/command/project/bean/CreateBeanCommand.java
  starter-cli/src/main/java/io/micronaut/starter/cli/command/project/job/CreateJobCommand.java
  starter-cli/src/main/java/io/micronaut/starter/cli/feature/grpc/CreateGrpcServiceCommand.java
  starter-cli/src/main/java/io/micronaut/starter/cli/feature/messaging/kafka/CreateKafkaListener.java
  starter-cli/src/main/java/io/micronaut/starter/cli/feature/messaging/kafka/CreateKafkaProducer.java
  starter-cli/src/main/java/io/micronaut/starter/cli/feature/messaging/nats/CreateNatsListener.java
  starter-cli/src/main/java/io/micronaut/starter/cli/feature/messaging/nats/CreateNatsProducer.java
  starter-cli/src/main/java/io/micronaut/starter/cli/feature/messaging/rabbitmq/CreateRabbitMQListener.java
  starter-cli/src/main/java/io/micronaut/starter/cli/feature/messaging/rabbitmq/CreateRabbitMQProducer.java
  starter-core/src/test/groovy/io/micronaut/starter/options/LanguageSpec.groovy
Labels: type: improvement

#413 feat: supported languages and default language for test framework
  starter-core/src/main/java/io/micronaut/starter/options/TestFramework.java
  starter-core/src/test/groovy/io/micronaut/starter/options/TestFrameworkSpec.groovy
Labels: type: improvement

#411 refactor: %s/isKotlinTest/isKotlinTestFramework
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/templates/annotationProcessor.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/templates/buildGradle.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/templates/testFrameworks.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/build/maven/templates/pom.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/test/TestFeature.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/test/TestFeatureSpec.groovy
Labels: type: improvement

#427 extract application/zip to constant
  starter-api/src/main/java/io/micronaut/starter/api/create/CreateController.java
Labels: type: improvement

#426 fix: del mn.security.token.jwt.cookie.enabled
  starter-core/src/main/java/io/micronaut/starter/feature/security/SecurityOAuth2.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/security/SecurityOauth2Spec.groovy
Labels: type: improvement
