Repository micronaut-projects/micronaut-starter, pull requests merged in 2021-09, with the labels that each got.

#899 Upgrade to gradle plugin 2.0.4
  starter-core/src/main/resources/pom.xml
Labels: type: dependency-upgrade

#918 Publish build scans on ge.micraunaut.io
  settings.gradle
Labels: relates-to: build

#915 fix: replaces com.fizzed with nu.studer rocker
  starter-core/src/main/java/io/micronaut/starter/feature/view/Rocker.java
  starter-core/src/main/java/io/micronaut/starter/feature/view/gradlePluginRocker.rocker.raw
  starter-core/src/main/resources/pom.xml
  starter-core/src/test/groovy/io/micronaut/starter/feature/view/RockerSpec.groovy
  test-core/src/test/groovy/io/micronaut/starter/core/test/feature/views/RockerSpec.groovy
Labels: type: bug
