Repository micronaut-projects/micronaut-starter, pull requests merged in 2022-03, with the labels that each got.

#972 TOML configuration feature
  starter-core/src/main/java/io/micronaut/starter/feature/config/Toml.java
  starter-core/src/main/java/io/micronaut/starter/template/TomlStringOutputUtil.java
  starter-core/src/main/java/io/micronaut/starter/template/TomlTemplate.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/config/TomlSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/template/TomlTemplateSpec.groovy
  test-core/src/test/groovy/io/micronaut/starter/core/test/feature/configuration/ConfigurationSpec.groovy
Labels: type: enhancement

#1094 upgrade from 7.3.1 to Gradle 7.4.1
  DockerfileCloudRun
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  starter-core/src/main/resources/gradle/wrapper/gradle-wrapper.jar
  starter-core/src/main/resources/gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#1087 Upgrade to the Gradle plugins 3.3.0
  starter-core/src/main/resources/pom.xml
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/MicronautAotBuildPluginSpec.groovy
Labels: type: dependency-upgrade

#1130 Move mongo-data out of preview
  starter-core/src/main/java/io/micronaut/starter/feature/database/DataMongo.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/MongoSpec.groovy
Labels: relates-to: build

#1132 Publish snapshots for 3.4.x
  .github/workflows/analytics-gcr-snapshot.yml
  .github/workflows/aws-lambda-snapshot.yml
  .github/workflows/gcf-snapshot.yml
  .github/workflows/gcr-snapshot.yml
  .github/workflows/mn-linux-snapshot.yml
  .github/workflows/mn-macos-snapshot.yml
  .github/workflows/mn-windows-snapshot.yml
Labels: relates-to: build
