Repository micronaut-projects/micronaut-starter, pull requests merged in 2022-01, with the labels that each got.

#1020 Upgrade to the build plugins 5.1.1
  .github/workflows/analytics-gcr-snapshot.yml
  .github/workflows/aws-lambda-snapshot.yml
  .github/workflows/azure-function-snapshot.yml
  .github/workflows/gcf-snapshot.yml
  .github/workflows/gcr-snapshot.yml
  .github/workflows/gradle-func.yml
  .github/workflows/gradle.yml
  .github/workflows/mavenCentral.yml
  .github/workflows/mn-linux-snapshot.yml
  .github/workflows/mn-macos-snapshot.yml
  .github/workflows/mn-windows-snapshot.yml
  .github/workflows/release.yml
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.internal.build.starter-cli-module.gradle
  buildSrc/src/main/groovy/io.micronaut.internal.build.starter-openapi-module.gradle
  buildSrc/src/main/groovy/io.micronaut.internal.starter.aggregator.gradle
  buildSrc/src/main/groovy/io.micronaut.internal.starter.base-module.gradle
  buildSrc/src/main/groovy/io.micronaut.internal.starter.convention.gradle
  buildSrc/src/main/groovy/io.micronaut.internal.starter.test-module.gradle
  buildSrc/src/main/groovy/io/micronaut/internal/starter/tasks/GenerateManpageAsciidoc.java
  buildSrc/src/main/groovy/io/micronaut/internal/starter/tasks/PicocliBuildCompletionTask.java
  buildSrc/src/main/groovy/io/micronaut/internal/starter/tasks/WriteMicronautVersionInfoTask.java
  buildSrc/src/main/java/io/micronaut/starter/rocker/plugin/RockerConfiguration.java
  buildSrc/src/main/java/io/micronaut/starter/rocker/plugin/RockerPlugin.java
  buildSrc/src/main/java/io/micronaut/starter/rocker/plugin/RockerTask.java
  gradle.properties
  settings.gradle
  starter-analytics-postgres/build.gradle
  starter-api/build.gradle
  starter-aws-lambda/build.gradle
  starter-azure-function/build.gradle
  starter-cli/build.gradle
  starter-core/build.gradle
  starter-gcp-function/build.gradle
  starter-web-netty/build.gradle
  starter-web-servlet/build.gradle
  test-cli/build.gradle
  test-core/build.gradle
  test-utils/build.gradle
Labels: relates-to: build

#1036 Upgrade to Micronaut Gradle Plugin 3.2.0
  starter-core/src/main/resources/pom.xml
Labels: type: dependency-upgrade

#1027 Add support for Micronaut Serialization to Launch
  starter-core/src/main/java/io/micronaut/starter/feature/json/JacksonDatabindFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/json/JsonFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/json/SerializationBsonFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/json/SerializationFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/json/SerializationJacksonFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/json/SerializationJsonbFeature.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/json/JsonFeatureSpec.groovy
Labels: type: enhancement

#1044 Restrict the set of published modules
  buildSrc/src/main/groovy/io.micronaut.internal.build.starter-cli-module.gradle
  buildSrc/src/main/groovy/io.micronaut.internal.build.starter-openapi-module.gradle
  buildSrc/src/main/groovy/io.micronaut.internal.starter.base-module.gradle
  buildSrc/src/main/groovy/io.micronaut.internal.starter.published-module.gradle
  starter-core/build.gradle
Labels: relates-to: build

#1035 Add Netty max order config / fix config nesting
  starter-core/src/main/java/io/micronaut/starter/feature/config/Configuration.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/DataJdbc.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/jdbc/JdbcFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/server/Netty.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/config/Config4kSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/config/YamlSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/DataJdbcSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/server/NettySpec.groovy
Labels: type: improvement

#917 feat: adds GeneratorContext::addHelpLink
  starter-core/src/main/java/io/micronaut/starter/application/generator/GeneratorContext.java
  starter-core/src/main/java/io/micronaut/starter/feature/function/azure/AbstractAzureFunction.java
  starter-core/src/main/java/io/micronaut/starter/feature/grpc/Grpc.java
  starter-core/src/main/java/io/micronaut/starter/feature/jib/Jib.java
  starter-core/src/main/java/io/micronaut/starter/feature/other/OpenRewrite.java
  starter-core/src/main/java/io/micronaut/starter/feature/other/ShadePlugin.java
  starter-core/src/main/java/io/micronaut/starter/feature/other/template/markdownLink.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/reloading/Jrebel.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/function/azure/AzureHttpFunctionSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/grpc/GrpcSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/jib/JibSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/other/OpenRewriteSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/other/ShadePluginSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/reloading/JrebelSpec.groovy
Labels: type: improvement

#1049 Switch to using BOM versions of the depenendencies
  starter-core/src/main/java/io/micronaut/starter/feature/other/template/readme.rocker.raw
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/gradle/GradleSpec.groovy
  starter-web-servlet/build.gradle
Labels: relates-to: build
