Repository micronaut-projects/micronaut-starter, pull requests merged in 2022-10, with the labels that each got.

#1460 Add allow-pool-suspension when Crac and Hikari are both selected
  starter-core/src/main/java/io/micronaut/starter/feature/crac/Crac.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/jdbc/Hikari.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/crac/CracSpec.groovy
Labels: type: enhancement

#1482 fix: command line app generation without test framework flag
  starter-core/src/main/java/io/micronaut/starter/application/ContextFactory.java
  starter-core/src/main/java/io/micronaut/starter/feature/build/BuildFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/Gradle.java
  starter-core/src/main/java/io/micronaut/starter/feature/build/maven/Maven.java
  starter-core/src/main/java/io/micronaut/starter/feature/test/KoTest.java
  starter-core/src/main/java/io/micronaut/starter/feature/test/Mockk.java
  starter-core/src/test/groovy/io/micronaut/starter/application/ContextFactorySpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/gradle/GradleSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/maven/MavenSpec.groovy
Labels: type: bug

#1491 Fix TestResources and Serde combination in Maven builds
  starter-core/src/main/java/io/micronaut/starter/feature/json/SerializationFeature.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/json/JsonFeatureSpec.groovy
Labels: type: bug

#1501 build: Update SnakeYML to 1.33
  starter-cli/build.gradle
  starter-core/build.gradle
Labels: type: dependency-upgrade

#1493 bug: Use correct serialization annotation in default/function
  starter-core/src/main/java/io/micronaut/starter/feature/function/AbstractFunctionFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/GoogleCloudFunctionFeatureValidator.java
  starter-core/src/main/java/io/micronaut/starter/feature/function/template/http/httpFunctionGroovyController.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/function/template/http/httpFunctionJavaController.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/function/template/http/httpFunctionKotlinController.rocker.raw
  starter-core/src/test/groovy/io/micronaut/starter/feature/function/azure/AzureCloudFunctionSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/function/gcp/GoogleCloudFunctionSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/function/oraclefunction/OracleFunctionSpec.groovy
  test-cloud/src/test/groovy/io/micronaut/starter/core/test/cloud/azure/CreateAzureFunctionSpec.groovy
  test-cloud/src/test/groovy/io/micronaut/starter/core/test/cloud/oracecloud/CreateOracleFunctionSpec.groovy
Labels: type: bug

#1506 Fix TestResources with Hibernate Reactive
  starter-core/src/main/java/io/micronaut/starter/build/dependencies/Dependency.java
  starter-core/src/main/java/io/micronaut/starter/build/dependencies/Phase.java
  starter-core/src/main/java/io/micronaut/starter/build/dependencies/Scope.java
  starter-core/src/main/java/io/micronaut/starter/build/gradle/GradleConfiguration.java
  starter-core/src/main/java/io/micronaut/starter/feature/build/MicronautBuildPlugin.java
  starter-core/src/main/java/io/micronaut/starter/feature/build/maven/templates/pom.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/database/HibernateReactiveFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/MariaDB.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/MySQL.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/Oracle.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/PostgreSQL.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/SQLServer.java
  starter-core/src/main/java/io/micronaut/starter/feature/testresources/DbType.java
  starter-core/src/main/java/io/micronaut/starter/feature/testresources/TestResources.java
  starter-core/src/main/resources/pom.xml
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/DataHibernateReactiveSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/HibernateReactiveJpaSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/MySQLSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/testresources/DbTypeSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/database/DataHibernateReactiveSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/database/HibernateReactiveJpaSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/database/templates/book.rocker.raw
Labels: type: bug
