Repository micronaut-projects/micronaut-starter, pull requests merged in 2022-07, with the labels that each got.

#1295 Open Telemetry
  starter-core/src/main/java/io/micronaut/starter/build/dependencies/DefaultPomDependencyVersionResolver.java
  starter-core/src/main/java/io/micronaut/starter/build/dependencies/MicronautDependencyUtils.java
  starter-core/src/main/java/io/micronaut/starter/feature/config/Configuration.java
  starter-core/src/main/java/io/micronaut/starter/feature/gcp/GcpFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/AbstractOpenTelemetry.java
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetry.java
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetryAnnotations.java
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetryDependencyUtils.java
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetryExporterFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetryExporterGoogleCloudTrace.java
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetryExporterJaeger.java
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetryExporterLogging.java
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetryExporterOtlp.java
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetryExporterZipkin.java
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetryFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetryGoogleCloudTrace.java
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetryGrpc.java
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetryHttp.java
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetryJaeger.java
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetryXray.java
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetryZipkin.java
  starter-core/src/main/resources/pom.xml
  starter-core/src/test/groovy/io/micronaut/starter/ApplicationContextSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/opentelemetry/OpenTelemetryAnnotationsSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/opentelemetry/OpenTelemetryExporterGoogleCloudTraceSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/opentelemetry/OpenTelemetryExporterJaegerSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/opentelemetry/OpenTelemetryExporterLoggingSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/opentelemetry/OpenTelemetryExporterOtlpSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/opentelemetry/OpenTelemetryExporterZipkinSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/opentelemetry/OpenTelemetryGoogleCloudTraceSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/opentelemetry/OpenTelemetryGrpcSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/opentelemetry/OpenTelemetryHttpSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/opentelemetry/OpenTelemetryJaegerSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/opentelemetry/OpenTelemetrySpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/opentelemetry/OpenTelemetryXraySpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/opentelemetry/OpenTelemetryZipkinSpec.groovy
Labels: status: awaiting third-party

#1329 Update scans plugin and try to fix dependabot
  starter-core/src/main/resources/pom.xml
Labels: build: gradle

#1328 Upgrade to Gradle plugin 3.5.0
  settings.gradle
  starter-core/src/main/resources/pom.xml
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/MicronautAotSpec.groovy
Labels: type: dependency-upgrade

#1330 bug: Fix dependency exclusion for Gradle
  starter-core/src/main/java/io/micronaut/starter/build/gradle/GradleDependency.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/aws/DynamoDbSpec.groovy
Labels: type: bug

#1333 build: update to gradle 7.5
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  starter-core/src/main/resources/gradle/gradlew
  starter-core/src/main/resources/gradle/gradlew.bat
  starter-core/src/main/resources/gradle/wrapper/gradle-wrapper.jar
  starter-core/src/main/resources/gradle/wrapper/gradle-wrapper.properties
Labels: build: gradle

#1334 Upgrade to Gradle plugin 3.5.1
  settings.gradle
  starter-core/src/main/resources/pom.xml
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/MicronautAotSpec.groovy
Labels: type: dependency-upgrade
