Repository micronaut-projects/micronaut-starter, pull requests merged in 2022-09, with the labels that each got.

#1384 Upgrade to Gradle plugin 3.5.3
  settings.gradle
  starter-core/src/main/resources/pom.xml
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/MicronautAotSpec.groovy
Labels: type: dependency-upgrade

#1395 Add Object Storage features
  starter-core/src/main/java/io/micronaut/starter/feature/objectstorage/ObjectStorageAws.java
  starter-core/src/main/java/io/micronaut/starter/feature/objectstorage/ObjectStorageAzure.java
  starter-core/src/main/java/io/micronaut/starter/feature/objectstorage/ObjectStorageFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/objectstorage/ObjectStorageGcp.java
  starter-core/src/main/java/io/micronaut/starter/feature/objectstorage/ObjectStorageOracleCloud.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/objectstorage/ObjectStorageAwsSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/objectstorage/ObjectStorageAzureSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/objectstorage/ObjectStorageGcpSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/objectstorage/ObjectStorageOracleCloudSpec.groovy
Labels: type: enhancement

#1411 Add CRaC feature
  starter-core/src/main/java/io/micronaut/starter/build/dependencies/MicronautDependencyUtils.java
  starter-core/src/main/java/io/micronaut/starter/feature/crac/Crac.java
  starter-core/src/main/resources/pom.xml
  starter-core/src/test/groovy/io/micronaut/starter/feature/crac/CracSpec.groovy
Labels: type: enhancement

#1456 @MicronautTest(transactional = false) for data-mongodb-reactive and data-r2dbc
  starter-cli/src/main/java/io/micronaut/starter/cli/command/project/test/CreateTestCommand.java
  starter-cli/src/main/java/io/micronaut/starter/cli/feature/server/controller/CreateControllerCommand.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/DataMongoReactive.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/TransactionalNotSupported.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/r2dbc/DataR2dbc.java
  starter-core/src/main/java/io/micronaut/starter/feature/function/oraclefunction/OracleFunction.java
  starter-core/src/main/java/io/micronaut/starter/feature/lang/groovy/GroovyApplication.java
  starter-core/src/main/java/io/micronaut/starter/feature/lang/java/JavaApplication.java
  starter-core/src/main/java/io/micronaut/starter/feature/lang/kotlin/KotlinApplication.java
  starter-core/src/main/java/io/micronaut/starter/feature/server/template/groovyJunit.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/server/template/javaJunit.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/server/template/koTest.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/server/template/kotlinJunit.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/server/template/spock.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/test/template/groovyJunit.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/test/template/javaJunit.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/test/template/koTest.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/test/template/kotlinJunit.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/test/template/spock.rocker.raw
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/database/DataMongoReactiveSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/database/DataR2dbcSpec.groovy
Labels: type: bug
