Repository micronaut-projects/micronaut-starter, pull requests merged in 2022-11, with the labels that each got.

#1505 build: GraalVM to 22.3
  starter-web-netty/build.gradle
  test-buildtool/src/test/groovy/io/micronaut/starter/core/test/buildTool/MavenPackageSpec.groovy
Labels: relates-to: graal, type: dependency-upgrade

#1528 Switch to enable classpathInference for test resources
  starter-core/src/main/java/io/micronaut/starter/feature/build/maven/templates/pom.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/database/DataJdbc.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/DataJpa.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/DataMongo.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/HibernateReactiveFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/MongoReactive.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/MongoSync.java
  starter-core/src/main/java/io/micronaut/starter/feature/testresources/EaseTestingFeature.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/testresources/OptionalTestContainerSpec.groovy
Labels: type: bug

#1540 Update installHomebrew.adoc
  src/main/docs/guide/installation/installHomebrew.adoc
Labels: type: docs

#1542 Upgrade Gradle plugin to 3.6.5
  settings.gradle
  starter-core/src/main/resources/pom.xml
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/MicronautAotSpec.groovy
Labels: type: dependency-upgrade

#1526 Enable eager initialization of singletons with CRaC
  starter-core/src/main/java/io/micronaut/starter/feature/RequireEagerSingletonInitializationFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/crac/Crac.java
  starter-core/src/main/java/io/micronaut/starter/feature/lang/ApplicationRenderingContext.java
  starter-core/src/main/java/io/micronaut/starter/feature/lang/groovy/GroovyApplication.java
  starter-core/src/main/java/io/micronaut/starter/feature/lang/groovy/GroovyApplicationRenderingContext.java
  starter-core/src/main/java/io/micronaut/starter/feature/lang/groovy/application.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/lang/groovy/contextConfigurer.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/lang/java/JavaApplication.java
  starter-core/src/main/java/io/micronaut/starter/feature/lang/java/JavaApplicationRenderingContext.java
  starter-core/src/main/java/io/micronaut/starter/feature/lang/java/application.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/lang/java/contextConfigurer.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/lang/kotlin/KotlinApplication.java
  starter-core/src/main/java/io/micronaut/starter/feature/lang/kotlin/KotlinApplicationRenderingContext.java
  starter-core/src/main/java/io/micronaut/starter/feature/lang/kotlin/application.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/lang/kotlin/contextConfigurer.rocker.raw
  starter-core/src/test/groovy/io/micronaut/starter/feature/crac/CracSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/lang/JavaApplicationSpec.groovy
  test-cli/src/test/groovy/io/micronaut/starter/cli/test/CreateBeanSpec.groovy
  test-core/src/test/groovy/io/micronaut/starter/core/test/create/CreateCracAppSpec.groovy
Labels: type: enhancement

#1356 Add feature which generates a Gitlab-CI yaml file
  starter-core/src/main/java/io/micronaut/starter/feature/ci/workflows/gitlab/GitlabCiWorkflowFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/ci/workflows/gitlab/templates/gitlabci.rocker.raw
  starter-core/src/test/groovy/io/micronaut/starter/feature/ci/workflows/gitlab/GitlabWorkflowCISpec.groovy
Labels: type: improvement
