Repository micronaut-projects/micronaut-starter, pull requests merged in 2022-05, with the labels that each got.

#1194 Upgrade to Gradle plugin 3.4.0
  .github/workflows/analytics-gcr-snapshot.yml
  .github/workflows/aws-lambda-snapshot.yml
  .github/workflows/gcf-snapshot.yml
  .github/workflows/gcr-snapshot.yml
  .github/workflows/gradle-func.yml
  .github/workflows/gradle.yml
  settings.gradle
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/templates/micronautGradle.rocker.raw
  starter-core/src/main/resources/pom.xml
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/MicronautAotBuildPluginSpec.groovy
Labels: type: dependency-upgrade

#1229 Use TestFilters instead of --tests to appease Test Selection
  .github/workflows/gradle-func.yml
  test-core/build.gradle
Labels: relates-to: build

#1232 Micronaut Console Feature
  .github/workflows/gradle-func.yml
  starter-analytics-postgres/src/test/groovy/io/micronaut/starter/analytics/postgres/StoreGeneratedProjectStatsSpec.groovy
  starter-api/src/test/groovy/io/micronaut/starter/api/FeatureControllerSpec.groovy
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/console/Console.java
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/console/template/consoleGroovyDsl.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/console/template/consoleGroovyHttp.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/console/template/consoleKotlinHttp.rocker.raw
  starter-core/src/main/resources/pom.xml
  starter-core/src/test/groovy/io/micronaut/starter/feature/agorapulse/console/ConsoleSpec.groovy
  test-core/build.gradle
  test-core/src/test/groovy/io/micronaut/starter/core/test/feature/agorapulse/console/ConsoleSpec.groovy
Labels: type: enhancement

#1237 Extract the picocli version from the pico bom
  starter-core/build.gradle
Labels: relates-to: build

#1234 Micronaut Worker Feature
  starter-api/src/test/groovy/io/micronaut/starter/api/FeatureControllerSpec.groovy
  starter-core/src/main/java/io/micronaut/starter/feature/Category.java
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/Worker.java
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/emailDigestDistributedJobGroovy.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/emailDigestDistributedJobJava.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/emailDigestDistributedJobKotlin.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/emailDigestDistributedJobSpecGroovy.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/emailDigestDistributedJobTestJava.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/emailDigestDistributedJobTestKotest.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/emailDigestDistributedJobTestKotlin.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/emailDigestServiceGroovy.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/emailDigestServiceJava.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/emailDigestServiceKotlin.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/emailDigestSimpleJobGroovy.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/emailDigestSimpleJobJava.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/emailDigestSimpleJobKotlin.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/emailDigestSimpleJobSpecGroovy.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/emailDigestSimpleJobTestJava.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/emailDigestSimpleJobTestKotest.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/emailDigestSimpleJobTestKotlin.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/fallbackEmailDigestServiceGroovy.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/fallbackEmailDigestServiceJava.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/agorapulse/worker/template/fallbackEmailDigestServiceKotlin.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/test/Awaitility.java
  starter-core/src/main/resources/pom.xml
  starter-core/src/test/groovy/io/micronaut/starter/feature/agorapulse/worker/WorkerSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/test/AwaitilitySpec.groovy
  test-core/src/test/groovy/io/micronaut/starter/core/test/feature/agorapulse/worker/WorkerSpec.groovy
Labels: type: enhancement

#1205 Add MicroStream features
  starter-core/src/main/java/io/micronaut/starter/feature/microstream/MicroStream.java
  starter-core/src/main/java/io/micronaut/starter/feature/microstream/MicroStreamCache.java
  starter-core/src/main/java/io/micronaut/starter/feature/microstream/MicroStreamFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/microstream/MicroStreamRest.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/microstream/MicroStreamSpec.groovy
Labels: status: awaiting third-party

#1269 Check for multiple modules when adding multi-pom, not just 1
  starter-core/src/main/java/io/micronaut/starter/feature/build/maven/Maven.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/maven/MavenSpec.groovy
Labels: type: bug
