Repository micronaut-projects/micronaut-starter, pull requests merged in 2022-02, with the labels that each got.

#1063 Add community flag for features
  starter-api/src/main/java/io/micronaut/starter/api/FeatureDTO.java
  starter-api/src/test/groovy/io/micronaut/starter/api/FeatureControllerSpec.groovy
  starter-cli/src/main/java/io/micronaut/starter/cli/command/ListFeatures.java
  starter-cli/src/test/groovy/io/micronaut/starter/cli/command/CreateAppCommandSpec.groovy
  starter-core/src/main/java/io/micronaut/starter/feature/Feature.java
  starter-core/src/main/java/io/micronaut/starter/feature/camunda/Camunda.java
  starter-core/src/main/java/io/micronaut/starter/feature/camunda/CamundaExternalWorker.java
  starter-core/src/main/java/io/micronaut/starter/feature/camunda/Zeebe.java
Labels: type: enhancement

#1064 fix: correct email-ses dependency
  starter-core/src/main/java/io/micronaut/starter/feature/email/AmazonSesEmailFeature.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/email/EmailFeatureSpec.groovy
Labels: type: bug

#1068 Fix snapshot lambda action
  .github/workflows/aws-lambda-snapshot.yml
Labels: relates-to: build

#1071 Upgrade to Gradle Plugin 3.2.2
  starter-core/src/main/resources/pom.xml
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/MicronautAotBuildPluginSpec.groovy
Labels: type: dependency-upgrade
