Repository micronaut-projects/micronaut-starter, pull requests merged in 2023-03, with the labels that each got.

#1649 Fix AOT Maven feature
  starter-core/src/main/java/io/micronaut/starter/feature/build/MicronautAot.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/MicronautAotSpec.groovy
Labels: type: bug

#1665 Update Spock to the latest
  gradle.properties
  starter-cli/src/test/groovy/io/micronaut/starter/cli/command/CreateLambdaBuilderCommandSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/options/BuildToolSpec.groovy
Labels: relates-to: build

#1673 Show the available JDK options in the CLI --help
  starter-cli/src/main/java/io/micronaut/starter/cli/MicronautStarter.java
  starter-cli/src/main/java/io/micronaut/starter/cli/command/CreateCommand.java
  starter-cli/src/main/java/io/micronaut/starter/cli/command/JdkVersionCandidates.java
Labels: type: improvement
