Repository micronaut-projects/micronaut-starter, pull requests merged in 2023-11, with the labels that each got.

#2157 Fix gradle configuration for Kotlin with Java 21 and update to 1.9.20
  gradle/templates.versions.toml
  starter-core/src/main/java/io/micronaut/starter/feature/build/KotlinSupportFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/templates/buildGradle.rocker.raw
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/KaptSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/gradle/GradleSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/test/SpockSpec.groovy
Labels: lang: kotlin, build: gradle

#2169 Update KSP to 1.9.20-1.0.14
  gradle/templates.versions.toml
Labels: lang: kotlin

#2173 Data data-tx if hibernate-jpa
  starter-core/src/main/java/io/micronaut/starter/application/generator/GeneratorContext.java
  starter-core/src/main/java/io/micronaut/starter/build/dependencies/MicronautDependencyUtils.java
  starter-core/src/main/java/io/micronaut/starter/feature/build/MicronautBuildPlugin.java
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/MicronautApplicationGradlePlugin.java
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/templates/micronautGradle.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/database/DataFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/HibernateJpa.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/gradle/GradleSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/BaseHibernateReactiveSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/DataHibernateReactiveSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/DataJdbcSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/DataJpaSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/HibernateJpaSpec.groovy
Labels: type: improvement

#2184 don’t add flyway postgres until Micronaut Flyway 7
  starter-core/src/main/java/io/micronaut/starter/feature/migration/Flyway.java
  starter-core/src/main/java/io/micronaut/starter/util/VersionInfo.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/migration/FlywaySpec.groovy
Labels: type: bug

#2200 Update starter lambda features to support 21
  gradle.properties
  gradle/templates.versions.toml
  starter-aws-cdk/build.gradle.kts
  starter-core/src/main/java/io/micronaut/starter/feature/aws/AwsLambdaFeatureValidator.java
  starter-core/src/main/java/io/micronaut/starter/feature/build/MicronautBuildPlugin.java
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/MicronautApplicationGradlePlugin.java
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/templates/micronautGradle.rocker.raw
  starter-core/src/test/groovy/io/micronaut/starter/feature/function/awslambda/AwsLambdaSpec.groovy
Labels: type: enhancement
