Repository micronaut-projects/micronaut-starter, pull requests merged in 2023-12, with the labels that each got.

#2194 Create features for EclipseStore
  starter-core/src/main/java/io/micronaut/starter/build/dependencies/MicronautDependencyUtils.java
  starter-core/src/main/java/io/micronaut/starter/feature/eclipsestore/EclipseStore.java
  starter-core/src/main/java/io/micronaut/starter/feature/eclipsestore/EclipseStoreFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/eclipsestore/EclipseStoreRest.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/eclipsestore/EclipseStoreSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/eclipsestore/EclipseStoreFuncSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/eclipsestore/bookgroovy.rocker.raw
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/eclipsestore/bookjava.rocker.raw
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/eclipsestore/bookkotlin.rocker.raw
Labels: type: enhancement

#2219 Add micronaut-openapi-adoc feature (asciidoc conversion).
  starter-core/src/main/java/io/micronaut/starter/feature/other/OpenApiAdoc.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/other/OpenApiAdocSpec.groovy
Labels: type: enhancement

#2201 Telegram ChatBot support in Starter
  starter-core/src/main/java/io/micronaut/starter/application/generator/GeneratorContext.java
  starter-core/src/main/java/io/micronaut/starter/build/dependencies/MicronautDependencyUtils.java
  starter-core/src/main/java/io/micronaut/starter/feature/Category.java
  starter-core/src/main/java/io/micronaut/starter/feature/CodeContributingFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/awsalexa/AwsAlexa.java
  starter-core/src/main/java/io/micronaut/starter/feature/buildless/Buildless.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/ChatBotType.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/ChatBots.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/ChatBotsFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/telegram/ChatBotsTelegram.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/telegram/TelegramAwsChatBot.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/telegram/TelegramAzureChatBot.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/telegram/TelegramGcpChatBot.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/telegram/TelegramHttpChatBot.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/about.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/aboutCommandHandlerGroovy.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/aboutCommandHandlerGroovyJunit.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/aboutCommandHandlerGroovySpock.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/aboutCommandHandlerJava.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/aboutCommandHandlerJavaJunit.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/aboutCommandHandlerKotlin.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/aboutCommandHandlerKotlinJunit.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/awsCdkReadme.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/awsReadme.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/azureReadme.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/controllerGroovyJunit.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/controllerGroovySpock.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/controllerJavaJunit.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/controllerKotlinJunit.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/controllerReadme.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/finalCommandHandlerGroovy.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/finalCommandHandlerJava.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/finalCommandHandlerKotlin.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/gcpReadme.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/mockAboutCommandJson.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/template/telegramReadme.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/function/AbstractFunctionFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/function/awslambda/AwsLambda.java
  starter-core/src/main/java/io/micronaut/starter/feature/function/azure/AbstractAzureFunction.java
  starter-core/src/main/java/io/micronaut/starter/feature/function/azure/AzureBuildCommandUtils.java
  starter-core/src/main/java/io/micronaut/starter/feature/function/azure/AzureRawFunction.java
  starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/GcpCloudFunctionBuildCommandUtils.java
  starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/GoogleCloudFunction.java
  starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/GoogleCloudRawFunction.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/chatbots/BaseChatBotSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/chatbots/telegram/BaseTelegramChatBotSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/chatbots/telegram/TelegramAwsChatBotSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/chatbots/telegram/TelegramAzureChatBotSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/chatbots/telegram/TelegramGcpChatBotSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/chatbots/telegram/TelegramHttpChatBotSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/function/azure/AzureBuildCommandUtilsSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/function/gcp/GcpCloudFunctionBuildCommandUtilsSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/chatbots/TelegramAwsChatBotFunctionSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/chatbots/TelegramAzureChatBotFunctionSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/chatbots/TelegramControllerChatBotSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/chatbots/TelegramGcpChatBotFunctionSpec.groovy
Labels: type: enhancement

#2230 Add Redoc view feature for OpenApi.
  starter-core/src/main/java/io/micronaut/starter/feature/other/Redoc.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/other/RedocSpec.groovy
Labels: type: enhancement

#2232 remove leading space
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/Gradle.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/KotlinSymbolProcessingSpec.groovy
Labels: type: improvement

#2244 test: JdkVersion serde test
  starter-api/src/test/groovy/io/micronaut/starter/api/JdkVersionSpec.groovy
  starter-web-netty/src/test/groovy/io/micronaut/starter/netty/JdkVersionSpec.groovy
Labels: type: improvement

#2245 Add `create-chatbot` command to CLI
  starter-cli/src/main/java/io/micronaut/starter/cli/MicronautStarter.java
  starter-cli/src/main/java/io/micronaut/starter/cli/command/BuilderCommand.java
  starter-cli/src/main/java/io/micronaut/starter/cli/command/CreateBuilderCommand.java
  starter-cli/src/main/java/io/micronaut/starter/cli/command/CreateChatBotBuilderCommand.java
  starter-cli/src/main/java/io/micronaut/starter/cli/command/CreateLambdaBuilderCommand.java
  starter-cli/src/main/java/io/micronaut/starter/cli/command/YesOrNo.java
  starter-cli/src/test/groovy/io/micronaut/starter/cli/command/CreateChatBotBuilderCommandSpec.groovy
Labels: type: enhancement, type: improvement

#2250 Fix asserj/junit error when creating a project
  starter-core/src/main/java/io/micronaut/starter/feature/test/JunitCompanionFeatureValidator.java
  starter-core/src/main/java/io/micronaut/starter/feature/view/ViewsFieldsetTck.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/test/AssertJSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/view/ViewsFieldsetTckSpec.groovy
Labels: type: bug

#2249 Fix Kotlin DSL when specifying docker image names
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/templates/buildGradle.rocker.raw
  starter-core/src/test/groovy/io/micronaut/starter/feature/function/oraclefunction/OracleFunctionSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/github/workflows/azure/AzureContainerInstanceWorkflowSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/github/workflows/docker/DockerRegistryWorkflowSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/github/workflows/docker/GraalVMDockerRegistryWorkflowSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/github/workflows/gcloud/GoogleCloudRunWorkflowSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/github/workflows/oci/OracleFunctionsWorkflowSpec.groovy
Labels: type: bug

#2251 Align apigatewayv2-integrations and apigatewayv2 to aws-cdk-lib
  gradle/templates.versions.toml
Labels: type: bug
