Repository micronaut-projects/micronaut-starter, pull requests merged in 2023-07, with the labels that each got.

#1944 Stop testResources config in Gradle when testcontainers used instead
  starter-core/src/main/java/io/micronaut/starter/feature/build/MicronautBuildPlugin.java
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/MicronautApplicationGradlePlugin.java
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/templates/micronautGradle.rocker.raw
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/MySQLSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/messaging/kafka/KafkaSpec.groovy
Labels: type: bug

#1956 AOT as a Default feature
  starter-core/src/main/java/io/micronaut/starter/feature/build/MicronautAot.java
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/templates/aotExtension.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/build/maven/templates/aot.rocker.raw
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/MicronautAotSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/messaging/kafka/KafkaSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/messaging/kafka/KafkaStreamsSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/messaging/rabbitmq/RabbitMQSpec.groovy
Labels: type: improvement

#1806 deploy to starter-latest
  .github/workflows/release.yml
Labels: status: next major version

#1967 Upgrade to Gradle plugin 4.0.1
  gradle/templates.versions.toml
  settings.gradle
Labels: type: dependency-upgrade, relates-to: build

#1972 remove micronaut.data.version property
  starter-core/src/main/java/io/micronaut/starter/feature/database/Data.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/DataHibernateReactiveSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/DataJdbcSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/DataJpaSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/r2dbc/DataR2dbcSpec.groovy
Labels: type: improvement

#1969 micronaut.core.version for micronaut-http-validation
  starter-core/src/main/java/io/micronaut/starter/feature/validator/MicronautHttpValidation.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/validator/MicronautHttpValidationSpec.groovy
Labels: type: bug
