Repository micronaut-projects/micronaut-starter, pull requests merged in 2023-09, with the labels that each got.

#2038 Remove ApplicationContextConfigurer from the service type list
  starter-core/src/main/java/io/micronaut/starter/feature/build/MicronautAot.java
  starter-core/src/test/resources/expected-aot-jar.properties
  starter-core/src/test/resources/expected-aot-native-image.properties
Labels: type: bug

#2030 Update Kotlin to 1.9.10 and KSP to 1.9.10-1.0.13
  gradle/templates.versions.toml
  starter-core/src/main/java/io/micronaut/starter/feature/view/JTE.java
  starter-core/src/main/java/io/micronaut/starter/feature/view/gradlePluginJTE.rocker.raw
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/views/JTESpec.groovy
Labels: lang: kotlin

#2050 Exclude inject from Jax-rs processor in maven
  starter-core/src/main/java/io/micronaut/starter/feature/jaxrs/JaxRs.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/jaxrs/JaxRsSecuritySpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/jaxrs/JaxRsSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/jaxrs/JaxRsSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/jaxrs/bookgroovy.rocker.raw
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/jaxrs/bookjava.rocker.raw
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/jaxrs/bookkotlin.rocker.raw
Labels: type: bug

#2039 Adding projectGroupId to micronaut starter
  buildSrc/src/main/groovy/io.micronaut.internal.starter.base-module.gradle
  gradle.properties
Labels: type: improvement

#2053 Exclude micronaut-inject for Maven tracing annotation processing
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetryAnnotations.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/opentelemetry/OpenTelemetryAnnotationsSpec.groovy
Labels: type: bug

#2052 Exclude dependencies in Maven for metrics annotation
  starter-core/src/main/java/io/micronaut/starter/feature/micrometer/MicrometerAnnotations.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/micrometer/MicrometerSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/micrometer/MicrometerSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/micrometer/bookgroovy.rocker.raw
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/micrometer/bookjava.rocker.raw
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/micrometer/bookkotlin.rocker.raw
Labels: type: bug

#2054 Exclude micronaut-core from microstream-annotation
  starter-core/src/main/java/io/micronaut/starter/feature/microstream/MicroStream.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/microstream/MicroStreamSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/microstream/MicroStreamSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/microstream/bookgroovy.rocker.raw
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/microstream/bookjava.rocker.raw
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/microstream/bookkotlin.rocker.raw
Labels: type: bug

#2057 Add MockServer java client feature.
  gradle/templates.versions.toml
  starter-core/src/main/java/io/micronaut/starter/feature/database/TestContainers.java
  starter-core/src/main/java/io/micronaut/starter/feature/test/MockServerClient.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/test/MockServerClientSpec.groovy
Labels: type: enhancement

#1961 r2dbc and db driver with test-resources needs `r2dbc.datasources.default.dialect` config.
  starter-core/src/main/java/io/micronaut/starter/feature/database/r2dbc/R2dbc.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/r2dbc/R2dbcSpec.groovy
Labels: type: bug

#2074 Enhancements to BuildTestVerifier API
  starter-core/src/test/groovy/io/micronaut/starter/build/BuildTestUtil.groovy
  starter-core/src/test/groovy/io/micronaut/starter/build/BuildTestVerifier.groovy
  starter-core/src/test/groovy/io/micronaut/starter/build/gradle/GradleBuildTestVerifier.groovy
  starter-core/src/test/groovy/io/micronaut/starter/build/gradle/GradleBuildTestVerifierSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/build/maven/MavenBuildTestVerifier.groovy
Labels: type: enhancement

#2073 Try to fix native compilation for 3.8.x branch
  .github/workflows/mn-linux-snapshot.yml
  .github/workflows/mn-macos-snapshot.yml
  .github/workflows/mn-windows-snapshot.yml
  .github/workflows/release.yml
  settings.gradle
  starter-cli/build.gradle
  starter-cli/src/main/resources/META-INF/native-image/io.micronaut.starter.cli/micronaut-starter-cli/native-image.properties
  starter-core/src/main/resources/pom.xml
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/MicronautAotSpec.groovy
  test-cli/src/test/groovy/io/micronaut/starter/cli/test/CreateControllerSpec.groovy
Labels: relates-to: graal
