Repository micronaut-projects/micronaut-starter, pull requests merged in 2023-10, with the labels that each got.

#2079 Community feature for slf4j-simple-logger
  gradle/templates.versions.toml
  starter-api/src/test/groovy/io/micronaut/starter/api/FeatureControllerSpec.groovy
  starter-core/src/main/java/io/micronaut/starter/feature/ThirdPartyLibraryFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/logging/Slf4jSimpleLogger.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/logging/Slf4jSimpleLoggerSpec.groovy
Labels: type: enhancement

#2095 enable logback coloring
  starter-core/src/main/java/io/micronaut/starter/feature/logging/Logback.java
  starter-core/src/main/java/io/micronaut/starter/feature/logging/template/logback.rocker.raw
  starter-core/src/test/groovy/io/micronaut/starter/feature/logging/LogbackSpec.groovy
Labels: type: improvement

#2104 ci: Manual Release workflow [ci skip]
  .github/workflows/release-manually.yml
Labels: relates-to: build

#2106 Fix Swagger
  starter-web-netty/src/main/resources/application.yml
  starter-web-netty/src/test/groovy/io/micronaut/starter/netty/OpenAPISpec.groovy
  starter-web-servlet/src/main/resources/application.properties
  starter-web-servlet/src/test/groovy/io/micronaut/starter/servlet/OpenAPISpec.groovy
Labels: type: docs

#2112 Control Panel feature adds Management feature automatically.
  starter-core/src/main/java/io/micronaut/starter/feature/dev/ControlPanel.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/dev/ControlPanelSpec.groovy
  starter-web-servlet/src/test/groovy/io/micronaut/starter/servlet/OpenAPISpec.groovy
Labels: type: improvement

#2125 fix: http client as compile for discovery-client
  starter-core/src/main/java/io/micronaut/starter/application/generator/GeneratorContext.java
  starter-core/src/main/java/io/micronaut/starter/feature/discovery/DiscoveryClient.java
  starter-core/src/main/java/io/micronaut/starter/feature/httpclient/HttpClientJdk.java
  starter-core/src/main/java/io/micronaut/starter/feature/other/HttpClientTest.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/discovery/DiscoveryClientSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/discovery/DiscoveryClientFunctionalSpec.groovy
Labels: type: bug

#2075 Fix native compilation for the 3.9.x branch
  .github/workflows/mn-linux-snapshot.yml
Labels: relates-to: graal

#2076 Fix native compilation for the 3.10.x branch
  .github/workflows/mn-linux-snapshot.yml
  .github/workflows/mn-macos-snapshot.yml
  .github/workflows/mn-windows-snapshot.yml
  .github/workflows/release.yml
  starter-cli/build.gradle
  starter-cli/src/main/resources/META-INF/native-image/io.micronaut.starter.cli/micronaut-starter-cli/native-image.properties
Labels: relates-to: graal
