Repository micronaut-projects/micronaut-starter, pull requests merged in 2023-08, with the labels that each got.

#1979 Add endpoint to download analytics as excel
  starter-analytics-postgres/build.gradle.kts
  starter-analytics-postgres/src/main/java/io/micronaut/starter/analytics/postgres/AnalyticsController.java
  starter-analytics-postgres/src/main/java/io/micronaut/starter/analytics/postgres/ApplicationRepository.java
  starter-analytics-postgres/src/main/java/io/micronaut/starter/analytics/postgres/ExcelGenerator.java
  starter-analytics-postgres/src/main/java/io/micronaut/starter/analytics/postgres/StarterAnalyticsConfiguration.java
  starter-analytics-postgres/src/test/groovy/io/micronaut/starter/analytics/postgres/ExcelGeneratorSpec.groovy
  starter-analytics-postgres/src/test/groovy/io/micronaut/starter/analytics/postgres/GenerateExcelSpec.groovy
  starter-analytics-postgres/src/test/groovy/io/micronaut/starter/analytics/postgres/StoreGeneratedProjectStatsSpec.groovy
Labels: type: enhancement

#1992 ci: do sdkMinorRelease not sdkMajorRelease [ci skip]
  .github/workflows/release.yml
Labels: relates-to: build

#1980 Secure analytics endpoints with an API Key
  starter-analytics-postgres/build.gradle.kts
  starter-analytics-postgres/src/main/java/io/micronaut/starter/analytics/postgres/AnalyticsController.java
  starter-analytics-postgres/src/main/java/io/micronaut/starter/analytics/postgres/security/ApiKeyConfiguration.java
  starter-analytics-postgres/src/main/java/io/micronaut/starter/analytics/postgres/security/ApiKeyRepository.java
  starter-analytics-postgres/src/main/java/io/micronaut/starter/analytics/postgres/security/ApiKeyTokenReader.java
  starter-analytics-postgres/src/main/java/io/micronaut/starter/analytics/postgres/security/ApiKeyTokenValidator.java
  starter-analytics-postgres/src/test/groovy/io/micronaut/starter/analytics/postgres/GenerateExcelSpec.groovy
  starter-analytics-postgres/src/test/groovy/io/micronaut/starter/analytics/postgres/StoreGeneratedProjectStatsSpec.groovy
  starter-web-netty/src/main/java/io/micronaut/starter/netty/analytics/AnalyticsClient.java
  starter-web-netty/src/test/groovy/io/micronaut/starter/netty/ReportAnalyticsNoApiKeySpec.groovy
  starter-web-netty/src/test/groovy/io/micronaut/starter/netty/ReportAnalyticsSpec.groovy
  starter-web-netty/src/test/groovy/io/micronaut/starter/netty/ReportAnalyticsWrongApiKeySpec.groovy
Labels: type: enhancement

#1995 return core and platform to snapshot after release
  .github/workflows/release.yml
  build.gradle
  buildSrc/src/main/groovy/io/micronaut/internal/starter/tasks/GradlePropertiesNextSnapshot.groovy
  buildSrc/src/main/groovy/io/micronaut/internal/starter/tasks/Snapshot.groovy
  buildSrc/src/main/groovy/io/micronaut/internal/starter/tasks/SoftwareVersion.groovy
Labels: relates-to: build

#2004 Re-enable serialization-jackson with GCP function
  starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/GoogleCloudFunctionFeatureValidator.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/function/gcp/GoogleCloudFunctionSpec.groovy
Labels: type: improvement

#2005 Add testcontainers kafka dependency to kafka+testcontainers features.
  starter-core/src/main/java/io/micronaut/starter/build/dependencies/MicronautDependencyUtils.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/TestContainers.java
  starter-core/src/main/java/io/micronaut/starter/feature/messaging/kafka/Kafka.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/messaging/kafka/KafkaSpec.groovy
Labels: type: improvement

#2025 Stop hardcoding a version of micronaut-security-aot
  gradle/templates.versions.toml
  starter-core/src/main/java/io/micronaut/starter/build/maven/GroovyMavenPlusPlugin.java
  starter-core/src/main/java/io/micronaut/starter/feature/build/MicronautAot.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/MicronautAotSpec.groovy
Labels: type: bug

#2028 Add documentation about what a Community Feature is.
  src/main/docs/guide/communityFeature.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs
