Repository micronaut-projects/micronaut-starter, pull requests merged in 2023-04, with the labels that each got.

#1701 pin baseImage to amazonlinux:2
  starter-core/src/main/java/io/micronaut/starter/feature/build/MicronautBuildPlugin.java
  starter-core/src/main/java/io/micronaut/starter/feature/build/gradle/templates/micronautGradle.rocker.raw
  starter-core/src/test/groovy/io/micronaut/starter/feature/function/awslambda/AwsLambdaSpec.groovy
Labels: type: bug

#1703 don't offer function-url when selecting controllers style
  starter-cli/src/main/java/io/micronaut/starter/cli/command/CreateLambdaBuilderCommand.java
  starter-cli/src/test/groovy/io/micronaut/starter/cli/command/CreateLambdaBuilderCommandSpec.groovy
Labels: type: bug

#1748 Fix native starter-web-netty
  starter-api/src/main/resources/META-INF/native-image/io.micronaut.starter.api/micronaut-starter-api/native-image.properties
  starter-core/build.gradle
Labels: relates-to: graal

#1749 Switch to use nativeCompile for the mn binary
  .github/workflows/mn-linux-snapshot.yml
  .github/workflows/mn-macos-snapshot.yml
  .github/workflows/mn-windows-snapshot.yml
  starter-cli/build.gradle
  starter-cli/src/main/resources/META-INF/native-image/io.micronaut.starter.cli/micronaut-starter-cli/native-image.properties
  starter-core/src/main/java/io/micronaut/starter/feature/build/KotlinSupportFeature.java
Labels: relates-to: graal

#1753 support Java 17 runtime in CDK
  gradle/templates.versions.toml
  starter-cli/src/main/java/io/micronaut/starter/cli/command/CreateLambdaBuilderCommand.java
  starter-core/src/main/java/io/micronaut/starter/feature/aws/Cdk.java
  starter-core/src/main/java/io/micronaut/starter/feature/aws/template/cdkappstack.rocker.raw
  starter-core/src/test/groovy/io/micronaut/starter/feature/aws/CdkFeatureSpec.groovy
  test-buildtool/src/test/groovy/io/micronaut/starter/core/test/buildTool/MavenPackageSpec.groovy
  test-lambda.sh
Labels: type: improvement
