Repository micronaut-projects/micronaut-starter, pull requests merged in 2024-04, with the labels that each got.

#2435 fix broken ThymeleafSpec by syncing updated thymeleaf fieldset templates
  starter-core/src/main/resources/views/thymeleaf/fieldset/inputcheckbox.html
  starter-core/src/main/resources/views/thymeleaf/fieldset/inputradio.html
Labels: type: bug

#2439 bug: replace opentelemetry-extension-aws
  starter-core/src/main/java/io/micronaut/starter/feature/opentelemetry/OpenTelemetryXray.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/opentelemetry/OpenTelemetryXraySpec.groovy
  test-cloud/src/test/groovy/io/micronaut/starter/core/test/cloud/aws/TracingOpentelemetryXrayIntegrationSpec.groovy
Labels: type: bug

#2444 fix class-name in functions controllers
  starter-core/src/main/java/io/micronaut/starter/feature/function/AbstractFunctionFeature.java
  test-cloud/src/test/groovy/io/micronaut/starter/core/test/cloud/oracecloud/CreateOracleFunctionSpec.groovy
  test-utils/src/main/groovy/io/micronaut/starter/test/CommandSpec.groovy
Labels: type: bug

#2466 Remove rxjava1 and rxjava2
  starter-core/src/main/java/io/micronaut/starter/feature/k8s/KubernetesRxJava2Client.java
  starter-core/src/main/java/io/micronaut/starter/feature/rxjava/RxJava1.java
  starter-core/src/main/java/io/micronaut/starter/feature/rxjava/RxJava2.java
  starter-core/src/main/java/io/micronaut/starter/feature/rxjava/RxJava2HttpClient.java
  starter-core/src/main/java/io/micronaut/starter/feature/rxjava/RxJava2HttpServerNetty.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/k8s/KubernetesRxJava2ClientSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/reactive/ReactiveFeatureSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/rxjava/RxJava1Spec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/rxjava/RxJava2HttpClientSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/rxjava/RxJava2Spec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/k8s/KubernetesClientSpec.groovy
Labels: type: breaking

#2465 Remove Microstream features (obsolete for Micronaut Framework 5).
  starter-core/src/main/java/io/micronaut/starter/build/dependencies/MicronautDependencyUtils.java
  starter-core/src/main/java/io/micronaut/starter/feature/microstream/MicroStream.java
  starter-core/src/main/java/io/micronaut/starter/feature/microstream/MicroStreamCache.java
  starter-core/src/main/java/io/micronaut/starter/feature/microstream/MicroStreamFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/microstream/MicroStreamRest.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/microstream/MicroStreamSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/microstream/MicroStreamSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/microstream/bookgroovy.rocker.raw
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/microstream/bookjava.rocker.raw
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/microstream/bookkotlin.rocker.raw
Labels: type: breaking

#2470 Add feature for micronaut-sourcegen.
  starter-core/src/main/java/io/micronaut/starter/build/dependencies/MicronautDependencyUtils.java
  starter-core/src/main/java/io/micronaut/starter/feature/sourcegen/SourcegenFeatureValidator.java
  starter-core/src/main/java/io/micronaut/starter/feature/sourcegen/SourcegenJava.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/sourcegen/SourcegenJavaSpec.groovy
Labels: type: enhancement

#2472 Update Gradle plugin to 4.3.8 for Micronaut 4.4.2
  .github/workflows/mn-macos-snapshot.yml
  gradle/templates.versions.toml
Labels: lang: kotlin
