Repository micronaut-projects/micronaut-starter, pull requests merged in 2024-02, with the labels that each got.

#2284 breaking(github): remove 'Push to GitHub' project generation
  starter-api/src/main/java/io/micronaut/starter/api/StarterConfiguration.java
  starter-api/src/main/java/io/micronaut/starter/api/create/github/GitHubCreateController.java
  starter-api/src/main/java/io/micronaut/starter/api/create/github/GitHubCreateDTO.java
  starter-api/src/main/java/io/micronaut/starter/api/create/github/GitHubCreateOperation.java
  starter-api/src/main/java/io/micronaut/starter/api/create/github/GitHubCreateService.java
  starter-api/src/main/java/io/micronaut/starter/api/create/github/GitHubRedirectService.java
  starter-api/src/test/groovy/io/micronaut/starter/api/create/github/GitHubCreateControllerSpec.groovy
  starter-api/src/test/groovy/io/micronaut/starter/api/create/github/GitHubCreateServiceTest.groovy
  starter-api/src/test/groovy/io/micronaut/starter/api/create/github/GitHubRedirectServiceTest.groovy
  starter-core/src/main/java/io/micronaut/starter/client/github/oauth/AccessToken.java
  starter-core/src/main/java/io/micronaut/starter/client/github/oauth/GitHubOAuthClient.java
  starter-core/src/main/java/io/micronaut/starter/client/github/oauth/GitHubOAuthOperations.java
  test-suite-graal/src/test/java/example/GitHubApiClientMock.java
  test-suite-graal/src/test/java/example/GitHubOAuthClientMock.java
  test-suite-graal/src/test/java/example/StarterWebNettyTest.java
Labels: type: breaking

#2192 Convert JdkVersion from enum to class
  config/checkstyle/suppressions.xml
  starter-api/build.gradle
  starter-api/src/main/java/io/micronaut/starter/api/FeatureDTO.java
  starter-api/src/main/java/io/micronaut/starter/api/JdkVersionDTO.java
  starter-api/src/main/java/io/micronaut/starter/api/SelectOptionsDTO.java
  starter-api/src/test/groovy/io/micronaut/starter/api/JdkVersionDTOSpec.groovy
  starter-cli/src/main/java/io/micronaut/starter/cli/command/CreateLambdaBuilderCommand.java
  starter-core/build.gradle
  starter-core/src/main/java/io/micronaut/starter/feature/build/maven/templates/pom.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/build/maven/templates/pomGeneric.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/function/azure/AbstractAzureFunction.java
  starter-core/src/main/java/io/micronaut/starter/feature/function/azure/AzureFunctionFeatureValidator.java
  starter-core/src/main/java/io/micronaut/starter/feature/function/gcp/GoogleCloudFunctionFeatureValidator.java
  starter-core/src/main/java/io/micronaut/starter/feature/github/workflows/templates/buildAndPushImage.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/options/JdkVersion.java
  starter-core/src/test/groovy/io/micronaut/starter/options/JdkVersionSpec.groovy
Labels: type: improvement

#2288 gradle 8.5
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  starter-core/src/main/resources/gradle/wrapper/gradle-wrapper.jar
  starter-core/src/main/resources/gradle/wrapper/gradle-wrapper.properties
Labels: type: enhancement

#2289 configuration for parameter store and secrets manager
  starter-core/src/main/java/io/micronaut/starter/feature/awsparameterstore/AwsParameterStore.java
  starter-core/src/main/java/io/micronaut/starter/feature/awssecretsmanager/AwsSecretsManager.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/awsparameterstore/AwsParameterStoreSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/awssecretsmanager/AwsSecretsManagerSpec.groovy
Labels: type: improvement

#2315 fix: Fix create-chatbot command in native image
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/ChatBots.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/basecamp/BasecampAwsChatBot.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/basecamp/BasecampAzureChatBot.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/basecamp/BasecampGcpChatBot.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/basecamp/BasecampHttpChatBot.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/basecamp/ChatBotsBasecamp.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/basecamp/template/basecampReadme.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/telegram/ChatBotsTelegram.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/telegram/TelegramAwsChatBot.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/telegram/TelegramAzureChatBot.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/telegram/TelegramGcpChatBot.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/telegram/TelegramHttpChatBot.java
  starter-core/src/main/java/io/micronaut/starter/feature/chatbots/telegram/template/telegramReadme.rocker.raw
  starter-core/src/main/java/io/micronaut/starter/template/RockerTemplate.java
  test-suite-graal/build.gradle
  test-suite-graal/src/test/java/io/micronaut/starter/cli/command/CommandSupplier.java
  test-suite-graal/src/test/java/io/micronaut/starter/cli/command/CreateChatBotBuilderCommandTest.java
  test-suite-graal/src/test/java/io/micronaut/starter/cli/command/CreateChatbotCommandCliOptions.java
  test-suite-graal/src/test/java/io/micronaut/starter/cli/command/LoggingConsoleOutput.java
  test-suite-graal/src/test/java/io/micronaut/starter/cli/command/NullOutputStream.java
  test-suite-graal/src/test/java/io/micronaut/starter/cli/command/StubbedLineReader.java
  test-suite-graal/src/test/java/io/micronaut/starter/cli/command/TemplateResolvingOutputHandler.java
Labels: relates-to: graal, type: bug

#2317 gradle plugin 4.3.2
  gradle/templates.versions.toml
Labels: type: dependency-upgrade

#2316 Test all combinations of create-aws-lambda cli command
  starter-cli/src/main/java/io/micronaut/starter/cli/command/CreateLambdaBuilderCommand.java
  starter-cli/src/test/groovy/io/micronaut/starter/cli/command/CreateLambdaBuilderCommandSpec.groovy
  test-suite-graal/src/test/java/io/micronaut/starter/cli/command/CreateLambdaCommandCliOptions.java
  test-suite-graal/src/test/java/io/micronaut/starter/cli/command/CreateLambdaCommandTest.java
Labels: relates-to: graal, relates-to: cli

#2319 fix: mn create fails since 4.3.0
  starter-cli/src/main/java/io/micronaut/starter/cli/command/BuilderCommand.java
Labels: type: bug

#2322 Selecting Java Version 21 generates build with jdk21 correctly.
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/KaptSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/gradle/GradleSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/maven/MavenSpec.groovy
Labels: type: bug

#2344 Selecting Java Version 21 (via REST endpoint) should generate build with jdk21
  starter-api/src/main/java/io/micronaut/starter/api/JdkVersionTypeConverter.java
  starter-api/src/main/java/io/micronaut/starter/api/preview/PreviewController.java
  starter-api/src/main/java/io/micronaut/starter/api/preview/PreviewOperations.java
  starter-api/src/test/groovy/io/micronaut/starter/api/JdkVersionDTOSpec.groovy
  starter-api/src/test/groovy/io/micronaut/starter/api/JdkVersionSpec.groovy
  starter-api/src/test/groovy/io/micronaut/starter/api/PreviewControllerSpec.groovy
  starter-api/src/test/groovy/io/micronaut/starter/api/ZipCreateControllerSpec.groovy
  starter-web-netty/src/test/groovy/io/micronaut/starter/netty/JdkVersionSpec.groovy
  starter-web-netty/src/test/groovy/io/micronaut/starter/netty/ReportAnalyticsNoApiKeySpec.groovy
  starter-web-netty/src/test/groovy/io/micronaut/starter/netty/ReportAnalyticsSpec.groovy
  starter-web-netty/src/test/groovy/io/micronaut/starter/netty/ReportAnalyticsWrongApiKeySpec.groovy
  starter-web-netty/src/test/groovy/io/micronaut/starter/netty/ZipCreateControllerSpec.groovy
  starter-web-servlet/src/test/groovy/io/micronaut/starter/servlet/ZipCreateControllerSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/database/DataHibernateReactiveSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/database/HibernateReactiveJpaSpec.groovy
Labels: type: bug

#2347 apply ojdbc11 not ojdbc8
  starter-core/src/main/java/io/micronaut/starter/feature/database/DatabaseDriverFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/Oracle.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/DataHibernateReactiveSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/HibernateReactiveJpaSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/OracleSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/messaging/jms/OracleAdvancedQueuingSpec.groovy
Labels: type: dependency-upgrade

#2348 docs: instruction for opening OpenAPI spec as yaml file is wrong.
  src/main/docs/guide/starterImpls/starterApi.adoc
Labels: type: docs

#2346 disable oracle for hibernate reactive
  starter-core/src/main/java/io/micronaut/starter/feature/database/DatabaseDriverFeature.java
  starter-core/src/main/java/io/micronaut/starter/feature/database/Oracle.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/DataHibernateReactiveSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/HibernateReactiveJpaSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/database/DataHibernateReactiveSpec.groovy
  test-features/src/test/groovy/io/micronaut/starter/core/test/feature/database/HibernateReactiveJpaSpec.groovy
Labels: type: bug

#2351 Default to Java 21 for project generation.
  starter-api/src/test/groovy/io/micronaut/starter/api/features/GoogleCloudFunctionSpec.groovy
  starter-api/src/test/groovy/io/micronaut/starter/api/options/SelectOptionsControllerTest.groovy
  starter-core/src/main/java/io/micronaut/starter/feature/build/MicronautBuildPlugin.java
  starter-core/src/main/java/io/micronaut/starter/options/MicronautJdkVersionConfiguration.java
  starter-core/src/test/groovy/io/micronaut/starter/feature/FeatureSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/gradle/GradleSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/build/maven/MavenSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/function/azure/AzureHttpFunctionSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/function/gcp/GoogleCloudFunctionSpec.groovy
  test-utils/src/main/groovy/io/micronaut/starter/test/CommandSpec.groovy
Labels: relates-to: build

#2356 Fix dependencies block view in gradle scripts.
  starter-api/build.gradle
  starter-aws-cdk/build.gradle.kts
  starter-aws-lambda/build.gradle
  starter-azure-function/build.gradle
  starter-cli/build.gradle
  starter-core/build.gradle
  starter-gcp-function/build.gradle
  starter-web-netty/build.gradle
  starter-web-servlet/build.gradle
  test-aws/build.gradle
  test-buildtool/build.gradle
  test-cli/build.gradle
  test-cloud/build.gradle
  test-core/build.gradle
  test-features/build.gradle
  test-suite-graal/build.gradle
  test-utils/build.gradle
Labels: relates-to: build

#2381 Revert "Revert "Fix MySQL dependency (#2064)""
  starter-core/src/main/java/io/micronaut/starter/feature/database/MySQL.java
  starter-core/src/test/groovy/io/micronaut/starter/build/dependencies/GradleDependencyComparatorSpec.groovy
  starter-core/src/test/groovy/io/micronaut/starter/feature/database/MySQLSpec.groovy
Labels: type: improvement
